import type { User, Appraisal, Attendance, Transfer, Leave } from "@/types"

// Hierarchy: Admin1 → Manager1/Manager2 → HR1-HR4 → Employee1-Employee8

export const mockUsers: User[] = [
  // Admin (1)
  {
    id: "admin1",
    employeeId: "ADM001",
    name: "Admin1",
    email: "admin@municipal.gov.in",
    password: "admin",
    role: "admin",
    department: "Administration",
    designation: "System Administrator",
    joiningDate: "2020-01-01",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "Municipal Headquarters",
    },
  },

  // Managers (2)
  {
    id: "manager1",
    employeeId: "MGR001",
    name: "Manager1",
    email: "manager1@municipal.gov.in",
    password: "Manager",
    role: "manager",
    department: "Operations",
    designation: "Operations Manager",
    joiningDate: "2019-05-10",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "Municipal Headquarters",
    },
  },
  {
    id: "manager2",
    employeeId: "MGR002",
    name: "Manager2",
    email: "manager2@municipal.gov.in",
    password: "Manager",
    role: "manager",
    department: "Operations",
    designation: "Operations Manager",
    joiningDate: "2019-06-15",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "Municipal Headquarters",
    },
  },

  // HRs Under Manager1 (2)
  {
    id: "hr1",
    employeeId: "HR001",
    name: "HR1",
    email: "hr1@municipal.gov.in",
    password: "Hr",
    role: "hr",
    department: "Human Resources",
    designation: "HR Specialist",
    joiningDate: "2018-03-20",
    managerId: "manager1",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "HR Department",
    },
  },
  {
    id: "hr2",
    employeeId: "HR002",
    name: "HR2",
    email: "hr2@municipal.gov.in",
    password: "Hr",
    role: "hr",
    department: "Human Resources",
    designation: "HR Specialist",
    joiningDate: "2018-04-10",
    managerId: "manager1",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "HR Department",
    },
  },

  // HRs Under Manager2 (2)
  {
    id: "hr3",
    employeeId: "HR003",
    name: "HR3",
    email: "hr3@municipal.gov.in",
    password: "Hr",
    role: "hr",
    department: "Human Resources",
    designation: "HR Specialist",
    joiningDate: "2018-05-15",
    managerId: "manager2",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "HR Department",
    },
  },
  {
    id: "hr4",
    employeeId: "HR004",
    name: "HR4",
    email: "hr4@municipal.gov.in",
    password: "Hr",
    role: "hr",
    department: "Human Resources",
    designation: "HR Specialist",
    joiningDate: "2018-06-20",
    managerId: "manager2",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "HR Department",
    },
  },

  // Employees Under HR1 (2)
  {
    id: "emp1",
    employeeId: "EMP001",
    name: "Employee1",
    email: "employee1@municipal.gov.in",
    password: "Employee",
    role: "employee",
    department: "Operations",
    designation: "Field Officer",
    joiningDate: "2021-01-15",
    hrId: "hr1",
    managerId: "manager1",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "Zone A",
    },
  },
  {
    id: "emp2",
    employeeId: "EMP002",
    name: "Employee2",
    email: "employee2@municipal.gov.in",
    password: "Employee",
    role: "employee",
    department: "Operations",
    designation: "Field Officer",
    joiningDate: "2021-02-20",
    hrId: "hr1",
    managerId: "manager1",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.614,
      lng: 77.21,
      name: "Zone A",
    },
  },

  // Employees Under HR2 (2)
  {
    id: "emp3",
    employeeId: "EMP003",
    name: "Employee3",
    email: "employee3@municipal.gov.in",
    password: "Employee",
    role: "employee",
    department: "Operations",
    designation: "Field Officer",
    joiningDate: "2021-03-10",
    hrId: "hr2",
    managerId: "manager1",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.615,
      lng: 77.211,
      name: "Zone B",
    },
  },
  {
    id: "emp4",
    employeeId: "EMP004",
    name: "Employee4",
    email: "employee4@municipal.gov.in",
    password: "Employee",
    role: "employee",
    department: "Operations",
    designation: "Field Officer",
    joiningDate: "2021-04-05",
    hrId: "hr2",
    managerId: "manager1",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.616,
      lng: 77.212,
      name: "Zone B",
    },
  },

  // Employees Under HR3 (2)
  {
    id: "emp5",
    employeeId: "EMP005",
    name: "Employee5",
    email: "employee5@municipal.gov.in",
    password: "Employee",
    role: "employee",
    department: "Operations",
    designation: "Field Officer",
    joiningDate: "2021-05-12",
    hrId: "hr3",
    managerId: "manager2",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.617,
      lng: 77.213,
      name: "Zone C",
    },
  },
  {
    id: "emp6",
    employeeId: "EMP006",
    name: "Employee6",
    email: "employee6@municipal.gov.in",
    password: "Employee",
    role: "employee",
    department: "Operations",
    designation: "Field Officer",
    joiningDate: "2021-06-08",
    hrId: "hr3",
    managerId: "manager2",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.618,
      lng: 77.214,
      name: "Zone C",
    },
  },

  // Employees Under HR4 (2)
  {
    id: "emp7",
    employeeId: "EMP007",
    name: "Employee7",
    email: "employee7@municipal.gov.in",
    password: "Employee",
    role: "employee",
    department: "Operations",
    designation: "Field Officer",
    joiningDate: "2021-07-22",
    hrId: "hr4",
    managerId: "manager2",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.619,
      lng: 77.215,
      name: "Zone D",
    },
  },
  {
    id: "emp8",
    employeeId: "EMP008",
    name: "Employee8",
    email: "employee8@municipal.gov.in",
    password: "Employee",
    role: "employee",
    department: "Operations",
    designation: "Field Officer",
    joiningDate: "2021-08-30",
    hrId: "hr4",
    managerId: "manager2",
    adminId: "admin1",
    assignedLocation: {
      lat: 28.62,
      lng: 77.216,
      name: "Zone D",
    },
  },
]

export const mockAttendance: Attendance[] = [
  {
    id: "1",
    employeeId: "EMP001",
    date: "2026-01-10",
    checkIn: "09:05",
    checkOut: "17:10",
    location: { lat: 28.6135, lng: 77.2087 },
    geoHazriCompliant: true,
    status: "present",
  },
  {
    id: "2",
    employeeId: "EMP001",
    date: "2026-01-11",
    checkIn: "09:20",
    checkOut: "17:00",
    location: { lat: 28.6137, lng: 77.2092 },
    geoHazriCompliant: false,
    status: "present",
  },
  {
    id: "3",
    employeeId: "EMP001",
    date: "2026-01-12",
    checkIn: "--",
    checkOut: "--",
    location: { lat: 0, lng: 0 },
    geoHazriCompliant: false,
    status: "absent",
  },
  {
    id: "4",
    employeeId: "EMP001",
    date: "2026-01-13",
    checkIn: "08:55",
    checkOut: "17:20",
    location: { lat: 28.6141, lng: 77.2093 },
    geoHazriCompliant: true,
    status: "present",
  },
  {
    id: "5",
    employeeId: "EMP001",
    date: "2026-01-14",
    checkIn: "09:35",
    checkOut: "17:05",
    location: { lat: 28.6142, lng: 77.2091 },
    geoHazriCompliant: false,
    status: "present",
  },
  {
    id: "6",
    employeeId: "EMP001",
    date: "2026-01-15",
    checkIn: "08:45",
    checkOut: "17:30",
    location: { lat: 28.6139, lng: 77.209 },
    geoHazriCompliant: true,
    status: "present",
  },
  {
    id: "7",
    employeeId: "EMP001",
    date: "2026-01-16",
    checkIn: "09:15",
    checkOut: "17:00",
    location: { lat: 28.614, lng: 77.2095 },
    geoHazriCompliant: false,
    status: "present",
  },
]

export const mockAppraisals: Appraisal[] = [
  {
    id: "1",
    employeeId: "ADM001",
    year: 2026,
    selfScore: 92,
    managerScore: 90,
    hrScore: 91,
    finalScore: 91,
    attendanceImpact: 0,
    geoHazriCompliance: 98,
    beatCoverage: 96,
    status: "completed",
    goals: [],
  },
  {
    id: "2",
    employeeId: "MGR001",
    year: 2026,
    selfScore: 88,
    managerScore: 86,
    hrScore: 87,
    finalScore: 87,
    attendanceImpact: 1,
    geoHazriCompliance: 95,
    beatCoverage: 93,
    status: "completed",
    goals: [],
  },
  {
    id: "3",
    employeeId: "MGR002",
    year: 2026,
    selfScore: 86,
    managerScore: 84,
    hrScore: 85,
    finalScore: 85,
    attendanceImpact: -1,
    geoHazriCompliance: 93,
    beatCoverage: 91,
    status: "completed",
    goals: [],
  },
  {
    id: "4",
    employeeId: "HR001",
    year: 2026,
    selfScore: 82,
    managerScore: 80,
    hrScore: 81,
    finalScore: 81,
    attendanceImpact: 0,
    geoHazriCompliance: 91,
    beatCoverage: 89,
    status: "completed",
    goals: [],
  },
  {
    id: "5",
    employeeId: "HR002",
    year: 2026,
    selfScore: 84,
    managerScore: 82,
    hrScore: 83,
    finalScore: 83,
    attendanceImpact: -1,
    geoHazriCompliance: 92,
    beatCoverage: 90,
    status: "completed",
    goals: [],
  },
  {
    id: "6",
    employeeId: "HR003",
    year: 2026,
    selfScore: 79,
    managerScore: 77,
    hrScore: 78,
    finalScore: 78,
    attendanceImpact: -3,
    geoHazriCompliance: 88,
    beatCoverage: 86,
    status: "submitted",
    goals: [],
  },
  {
    id: "7",
    employeeId: "HR004",
    year: 2026,
    selfScore: 81,
    managerScore: 79,
    hrScore: 80,
    finalScore: 80,
    attendanceImpact: -2,
    geoHazriCompliance: 90,
    beatCoverage: 88,
    status: "submitted",
    goals: [],
  },
  {
    id: "8",
    employeeId: "EMP001",
    year: 2026,
    selfScore: 85,
    managerScore: 78,
    hrScore: 80,
    finalScore: 81,
    attendanceImpact: -2,
    geoHazriCompliance: 92,
    beatCoverage: 88,
    status: "completed",
    goals: [
      {
        id: "g1",
        description: "Cover all assigned beats daily",
        targetDate: "2026-12-31",
        status: "completed",
        selfRating: 9,
        managerRating: 8,
      },
      {
        id: "g2",
        description: "Maintain 95% Geo-Hazri compliance",
        targetDate: "2026-12-31",
        status: "in-progress",
        selfRating: 8,
        managerRating: 7,
      },
    ],
  },
  {
    id: "9",
    employeeId: "EMP002",
    year: 2026,
    selfScore: 76,
    managerScore: 74,
    hrScore: 75,
    finalScore: 75,
    attendanceImpact: -4,
    geoHazriCompliance: 85,
    beatCoverage: 82,
    status: "draft",
    goals: [],
  },
  {
    id: "10",
    employeeId: "EMP003",
    year: 2026,
    selfScore: 87,
    managerScore: 85,
    hrScore: 86,
    finalScore: 86,
    attendanceImpact: 0,
    geoHazriCompliance: 94,
    beatCoverage: 92,
    status: "completed",
    goals: [],
  },
  {
    id: "11",
    employeeId: "EMP004",
    year: 2026,
    selfScore: 83,
    managerScore: 81,
    hrScore: 82,
    finalScore: 82,
    attendanceImpact: -1,
    geoHazriCompliance: 91,
    beatCoverage: 89,
    status: "completed",
    goals: [],
  },
  {
    id: "12",
    employeeId: "EMP005",
    year: 2026,
    selfScore: 80,
    managerScore: 78,
    hrScore: 79,
    finalScore: 79,
    attendanceImpact: -2,
    geoHazriCompliance: 89,
    beatCoverage: 87,
    status: "submitted",
    goals: [],
  },
  {
    id: "13",
    employeeId: "EMP006",
    year: 2026,
    selfScore: 72,
    managerScore: 70,
    hrScore: 71,
    finalScore: 71,
    attendanceImpact: -5,
    geoHazriCompliance: 82,
    beatCoverage: 80,
    status: "draft",
    goals: [],
  },
  {
    id: "14",
    employeeId: "EMP007",
    year: 2026,
    selfScore: 89,
    managerScore: 87,
    hrScore: 88,
    finalScore: 88,
    attendanceImpact: 1,
    geoHazriCompliance: 96,
    beatCoverage: 94,
    status: "completed",
    goals: [],
  },
  {
    id: "15",
    employeeId: "EMP008",
    year: 2026,
    selfScore: 77,
    managerScore: 75,
    hrScore: 76,
    finalScore: 76,
    attendanceImpact: -3,
    geoHazriCompliance: 87,
    beatCoverage: 85,
    status: "submitted",
    goals: [],
  },
]

export const mockTransfers: Transfer[] = [
  {
    id: "1",
    employeeId: "EMP001",
    fromLocation: "Zone A - Karol Bagh",
    toLocation: "Zone B - Rohini",
    requestDate: "2026-01-10",
    status: "pending",
    reason: "Family relocation",
    score: 78,
  },
]

export const mockLeaves: Leave[] = [
  {
    id: "1",
    employeeId: "EMP001",
    type: "casual",
    fromDate: "2026-02-01",
    toDate: "2026-02-02",
    reason: "Personal work",
    status: "approved",
    approvedBy: "Priya Sharma",
  },
]
